version: '3.7'

services:
  systeminformation:
    container_name: systeminformation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    env_file: .env
    restart: always
